# site properties and page defaults
title: Mikucki Lab
subtitle: Cool science in cold places
description: The Mikucki lab studies the interactions between microbes and their environment and how the impact of microbial metabolism is detectable on an ecosystem scale. Subglacial environments serve as our “model” ecosystem because their isolation and relatively simple food-webs allow for the study of microbially-mediated processes, which can be difficult to identify in more complex ecosystems.

header: images/PXL_20220918_231125205.jpg
footer: images/PXL_20220918_231125205.jpg
proofer: false

# site social media and other links
links:
  email: contact@wwallentDESCRIPTION=An engaging 1-3 sentence description of your lab..com
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: wwallentDESCRIPTION=An engaging 1-3 sentence description of your lab.
  twitter: wwallentDESCRIPTION=An engaging 1-3 sentence description of your lab.
  youtube: wwallentDESCRIPTION=An engaging 1-3 sentence description of your lab.

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
